{
	"font": 
	[ 
		{
			"fontName": "hero_default_social",
			"fontPackName": "Default Social Icons",
			"fontPackType": "social",
			"icons":[
				{
					"iconContent":"e600",
					"label":"social_blogger_circle",
					"position":"before"                      
				},
				{
					"iconContent":"e601",
					"label":"social_blogger_square", 
					"position":"before"                      
				},
				{
					"iconContent":"e602",
					"label":"social_blogger",  
					"position":"before"                     
				},
				{
					"iconContent":"e603",
					"label":"social_delicious_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e604",
					"label":"social_delicious_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e605",
					"label":"social_delicious",  
					"position":"before"                        
				},
				{
					"iconContent":"e606",
					"label":"social_deviantart_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e607",
					"label":"social_deviantart_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e608",
					"label":"social_deviantart",  
					"position":"before"                        
				},
				{
					"iconContent":"e609",
					"label":"social_dribbble_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e60a",
					"label":"social_dribbble_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e60b",
					"label":"social_dribbble", 
					"position":"before"                      
				},
				{
					"iconContent":"e60c",
					"label":"social_facebook_circle",  
					"position":"before"                     
				},
				{
					"iconContent":"e60d",
					"label":"social_facebook_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e60e",
					"label":"social_facebook",  
					"position":"before"                        
				},
				{
					"iconContent":"e60f",
					"label":"social_flickr_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e610",
					"label":"social_flickr_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e611",
					"label":"social_flickr",  
					"position":"before"                        
				},
				{
					"iconContent":"e612",
					"label":"social_googledrive_alt2",  
					"position":"before"                        
				},
				{
					"iconContent":"e613",
					"label":"social_googledrive_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e614",
					"label":"social_googledrive",  
					"position":"before"                        
				},
				{
					"iconContent":"e615",
					"label":"social_googleplus_circle", 
					"position":"before"                      
				},
				{
					"iconContent":"e616",
					"label":"social_googleplus_square",  
					"position":"before"                     
				},
				{
					"iconContent":"e617",
					"label":"social_googleplus",  
					"position":"before"                        
				},
				{
					"iconContent":"e618",
					"label":"social_instagram_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e619",
					"label":"social_instagram_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e61a",
					"label":"social_instagram",  
					"position":"before"                        
				},
				{
					"iconContent":"e61b",
					"label":"social_linkedin_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e61c",
					"label":"social_linkedin_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e61d",
					"label":"social_linkedin",  
					"position":"before"                        
				},
				{
					"iconContent":"e61e",
					"label":"social_myspace_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e61f",
					"label":"social_myspace_square", 
					"position":"before"                      
				},
				{
					"iconContent":"e620",
					"label":"social_myspace",  
					"position":"before"                     
				},
				{
					"iconContent":"e621",
					"label":"social_picassa_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e622",
					"label":"social_picassa_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e623",
					"label":"social_picassa",  
					"position":"before"                        
				},
				{
					"iconContent":"e624",
					"label":"social_pinterest_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e625",
					"label":"social_pinterest_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e626",
					"label":"social_pinterest",  
					"position":"before"                        
				},
				{
					"iconContent":"e627",
					"label":"social_rss_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e628",
					"label":"social_rss_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e629",
					"label":"social_rss", 
					"position":"before"                      
				},
				{
					"iconContent":"e62a",
					"label":"social_share_circle",  
					"position":"before"                     
				},
				{
					"iconContent":"e62b",
					"label":"social_share_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e62c",
					"label":"social_share",  
					"position":"before"                        
				},
				{
					"iconContent":"e62d",
					"label":"social_skype_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e62e",
					"label":"social_skype_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e62f",
					"label":"social_skype",  
					"position":"before"                        
				},
				{
					"iconContent":"e630",
					"label":"social_spotify_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e631",
					"label":"social_spotify_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e632",
					"label":"social_spotify",  
					"position":"before"                        
				},
				{
					"iconContent":"e633",
					"label":"social_stumbleupon_circle", 
					"position":"before"                      
				},
				{
					"iconContent":"e634",
					"label":"social_stumbleupon_square",  
					"position":"before"                     
				},
				{
					"iconContent":"e635",
					"label":"social_tumbleupon",  
					"position":"before"                        
				},
				{
					"iconContent":"e636",
					"label":"social_tumblr_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e637",
					"label":"social_tumblr_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e638",
					"label":"social_tumblr",  
					"position":"before"                        
				},
				{
					"iconContent":"e639",
					"label":"social_twitter_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e63a",
					"label":"social_twitter_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e63b",
					"label":"social_twitter",  
					"position":"before"                        
				},
				{
					"iconContent":"e63c",
					"label":"social_vimeo_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e63d",
					"label":"social_vimeo_square", 
					"position":"before"                      
				},
				{
					"iconContent":"e63e",
					"label":"social_vimeo",  
					"position":"before"                     
				},
				{
					"iconContent":"e63f",
					"label":"social_wordpress_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e640",
					"label":"social_wordpress_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e641",
					"label":"social_wordpress",  
					"position":"before"                        
				},
				{
					"iconContent":"e642",
					"label":"social_youtube_circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e643",
					"label":"social_youtube_square",  
					"position":"before"                        
				},
				{
					"iconContent":"e644",
					"label":"social_youtube",  
					"position":"before"                        
				}
			]
		},
		{
			"fontName": "hero_default_thin",
			"fontPackName": "Default Thin Icons",
			"fontPackType": "icons",
			"icons":[
				{
					"iconContent":"e600",
					"label":"arrow_carrot-down",
					"position":"after"                      
				},
				{
					"iconContent":"e601",
					"label":"arrow_carrot-left", 
					"position":"before"                      
				},
				{
					"iconContent":"e602",
					"label":"arrow_carrot-right",  
					"position":"after"                     
				},
				{
					"iconContent":"e603",
					"label":"icon_adjust-horiz",  
					"position":"before"                        
				},
				{
					"iconContent":"e604",
					"label":"icon_adjust-vert",  
					"position":"before"                     
				},
				{
					"iconContent":"e605",
					"label":"icon_archive_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e606",
					"label":"icon_bag_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e607",
					"label":"icon_balance",  
					"position":"before"                        
				},
				{
					"iconContent":"e608",
					"label":"icon_blocked",  
					"position":"before"                     
				},
				{
					"iconContent":"e609",
					"label":"icon_book_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e60a",
					"label":"icon_box-empty",  
					"position":"before"                     
				},
				{
					"iconContent":"e60b",
					"label":"icon_box-selected",  
					"position":"before"                        
				},
				{
					"iconContent":"e60c",
					"label":"icon_briefcase",  
					"position":"before"                     
				},
				{
					"iconContent":"e60d",
					"label":"icon_building",  
					"position":"before"                        
				},
				{
					"iconContent":"e60e",
					"label":"icon_calendar",  
					"position":"before"                     
				},
				{
					"iconContent":"e60f",
					"label":"icon_calulator",  
					"position":"before"                        
				},
				{
					"iconContent":"e610",
					"label":"icon_camera_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e611",
					"label":"icon_cart_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e612",
					"label":"icon_chat_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e613",
					"label":"icon_check_alt2",  
					"position":"before"                        
				},
				{
					"iconContent":"e614",
					"label":"icon_circle-empty",  
					"position":"before"                     
				},
				{
					"iconContent":"e615",
					"label":"icon_circle-slelected",  
					"position":"before"                        
				},
				{
					"iconContent":"e616",
					"label":"icon_clipboard",  
					"position":"before"                     
				},
				{
					"iconContent":"e617",
					"label":"icon_clock_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e618",
					"label":"icon_close_alt2",  
					"position":"before"                     
				},
				{
					"iconContent":"e619",
					"label":"icon_cloud_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e61a",
					"label":"icon_cloud-download_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e61b",
					"label":"icon_cloud-upload_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e61c",
					"label":"icon_comment_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e61d",
					"label":"icon_compass_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e61e",
					"label":"icon_cone_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e61f",
					"label":"icon_contacts_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e620",
					"label":"icon_creditcard",  
					"position":"before"                     
				},
				{
					"iconContent":"e621",
					"label":"icon_currency",  
					"position":"before"                        
				},
				{
					"iconContent":"e622",
					"label":"icon_cursor_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e623",
					"label":"icon_datareport",  
					"position":"before"                        
				},
				{
					"iconContent":"e624",
					"label":"icon_desktop",  
					"position":"before"                     
				},
				{
					"iconContent":"e625",
					"label":"icon_dislike",  
					"position":"before"                        
				},
				{
					"iconContent":"e626",
					"label":"icon_document_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e627",
					"label":"icon_documents_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e628",
					"label":"icon_drawer_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e629",
					"label":"icon_drive",  
					"position":"before"                        
				},
				{
					"iconContent":"e62a",
					"label":"icon_easel",  
					"position":"before"                     
				},
				{
					"iconContent":"e62b",
					"label":"icon_error-circle_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e62c",
					"label":"icon_film",  
					"position":"before"                     
				},
				{
					"iconContent":"e62d",
					"label":"icon_floppy",  
					"position":"before"                        
				},
				{
					"iconContent":"e62e",
					"label":"icon_flowchart",  
					"position":"before"                     
				},
				{
					"iconContent":"e62f",
					"label":"icon_folder-add_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e630",
					"label":"icon_folder-alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e631",
					"label":"icon_genius",  
					"position":"before"                        
				},
				{
					"iconContent":"e632",
					"label":"icon_gift_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e633",
					"label":"icon_globe-2",  
					"position":"before"                        
				},
				{
					"iconContent":"e634",
					"label":"icon_globe",  
					"position":"before"                     
				},
				{
					"iconContent":"e635",
					"label":"icon_headphones",  
					"position":"before"                        
				},
				{
					"iconContent":"e636",
					"label":"icon_heart_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e637",
					"label":"icon_hourglass",  
					"position":"before"                        
				},
				{
					"iconContent":"e638",
					"label":"icon_house_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e639",
					"label":"icon_id-2",  
					"position":"before"                        
				},
				{
					"iconContent":"e63a",
					"label":"icon_image",  
					"position":"before"                     
				},
				{
					"iconContent":"e63b",
					"label":"icon_info_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e63c",
					"label":"icon_key_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e63d",
					"label":"icon_laptop",  
					"position":"before"                        
				},
				{
					"iconContent":"e63e",
					"label":"icon_lightbulb_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e63f",
					"label":"icon_like",  
					"position":"before"                        
				},
				{
					"iconContent":"e640",
					"label":"icon_link_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e641",
					"label":"icon_lock_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e642",
					"label":"icon_lock-open_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e643",
					"label":"icon_mail_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e644",
					"label":"icon_map_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e645",
					"label":"icon_menu",  
					"position":"before"                        
				},
				{
					"iconContent":"e646",
					"label":"icon_minus_alt2",  
					"position":"before"                     
				},
				{
					"iconContent":"e647",
					"label":"icon_mug",  
					"position":"before"                        
				},
				{
					"iconContent":"e648",
					"label":"icon_paperclip",  
					"position":"before"                     
				},
				{
					"iconContent":"e649",
					"label":"icon_pause_alt2",  
					"position":"before"                        
				},
				{
					"iconContent":"e64a",
					"label":"icon_pens",  
					"position":"before"                     
				},
				{
					"iconContent":"e64b",
					"label":"icon_percent",  
					"position":"before"                        
				},
				{
					"iconContent":"e64c",
					"label":"icon_piechart",  
					"position":"before"                     
				},
				{
					"iconContent":"e64d",
					"label":"icon_pin_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e64e",
					"label":"icon_plus_alt2",  
					"position":"before"                     
				},
				{
					"iconContent":"e64f",
					"label":"icon_printer",  
					"position":"before"                        
				},
				{
					"iconContent":"e650",
					"label":"icon_pushpin_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e651",
					"label":"icon_puzzle",  
					"position":"before"                        
				},
				{
					"iconContent":"e652",
					"label":"icon_question_alt2",  
					"position":"before"                     
				},
				{
					"iconContent":"e653",
					"label":"icon_ribbon_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e654",
					"label":"icon_search2",  
					"position":"before"                     
				},
				{
					"iconContent":"e655",
					"label":"icon_shield",  
					"position":"before"                        
				},
				{
					"iconContent":"e656",
					"label":"icon_star_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e657",
					"label":"icon_stop_alt2",  
					"position":"before"                        
				},
				{
					"iconContent":"e658",
					"label":"icon_table",  
					"position":"before"                     
				},
				{
					"iconContent":"e659",
					"label":"icon_tag_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e65a",
					"label":"icon_tags_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e65b",
					"label":"icon_toolbox_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e65c",
					"label":"icon_trash_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e65d",
					"label":"icon_ul",  
					"position":"before"                        
				},
				{
					"iconContent":"e65e",
					"label":"icon_vol-mute_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e65f",
					"label":"icon_volume-high_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e660",
					"label":"icon_volume-low_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e661",
					"label":"icon_wallet",  
					"position":"before"                        
				},
				{
					"iconContent":"e662",
					"label":"icon_zoom-in_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e663",
					"label":"icon_zoom-out_alt",  
					"position":"before"                        
				}
			]
		},
		{
			"fontName": "hero_default_solid",
			"fontPackName": "Default Solid Icons",
			"fontPackType": "icons",
			"icons":[
				{
					"iconContent":"e600",
					"label":"arrow_carrot-down_alt",
					"position":"before"                      
				},
				{
					"iconContent":"e601",
					"label":"arrow_carrot-left_alt", 
					"position":"before"                      
				},
				{
					"iconContent":"e602",
					"label":"arrow_carrot-right_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e603",
					"label":"icon_archive",  
					"position":"before"                        
				},
				{
					"iconContent":"e604",
					"label":"icon_bag",  
					"position":"before"                        
				},
				{
					"iconContent":"e607",
					"label":"icon_balance",  
					"position":"before"                        
				},
				{
					"iconContent":"e608",
					"label":"icon_blocked",  
					"position":"before"                        
				},
				{
					"iconContent":"e605",
					"label":"icon_book",  
					"position":"before"                        
				},
				{
					"iconContent":"e606",
					"label":"icon_briefcase_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e609",
					"label":"icon_building_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e60a",
					"label":"icon_calculator_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e60e",
					"label":"icon_calendar", 
					"position":"before"                      
				},
				{
					"iconContent":"e60b",
					"label":"icon_camera",  
					"position":"before"                     
				},
				{
					"iconContent":"e60c",
					"label":"icon_cart",  
					"position":"before"                        
				},
				{
					"iconContent":"e60d",
					"label":"icon_chat",  
					"position":"before"                        
				},
				{
					"iconContent":"e60f",
					"label":"icon_check_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e616",
					"label":"icon_clipboard",  
					"position":"before"                        
				},
				{
					"iconContent":"e610",
					"label":"icon_clock",  
					"position":"before"                        
				},
				{
					"iconContent":"e611",
					"label":"icon_cloud-download",  
					"position":"before"                        
				},
				{
					"iconContent":"e612",
					"label":"icon_cloud-upload",  
					"position":"before"                        
				},
				{
					"iconContent":"e613",
					"label":"icon_cloud",  
					"position":"before"                        
				},
				{
					"iconContent":"e614",
					"label":"icon_cog", 
					"position":"before"                      
				},
				{
					"iconContent":"e615",
					"label":"icon_comment",  
					"position":"before"                     
				},
				{
					"iconContent":"e617",
					"label":"icon_compass",  
					"position":"before"                        
				},
				{
					"iconContent":"e618",
					"label":"icon_cone",  
					"position":"before"                        
				},
				{
					"iconContent":"e619",
					"label":"icon_contacts",  
					"position":"before"                        
				},
				{
					"iconContent":"e61a",
					"label":"icon_currency_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e61b",
					"label":"icon_datareport_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e624",
					"label":"icon_desktop",  
					"position":"before"                        
				},
				{
					"iconContent":"e61c",
					"label":"icon_dislike_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e61d",
					"label":"icon_document",  
					"position":"before"                        
				},
				{
					"iconContent":"e61e",
					"label":"icon_documents", 
					"position":"before"                      
				},
				{
					"iconContent":"e61f",
					"label":"icon_download",  
					"position":"before"                     
				},
				{
					"iconContent":"e620",
					"label":"icon_drawer",  
					"position":"before"                        
				},
				{
					"iconContent":"e621",
					"label":"icon_drive_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e622",
					"label":"icon_easel_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e623",
					"label":"icon_error-circle",  
					"position":"before"                        
				},
				{
					"iconContent":"e62c",
					"label":"icon_film",  
					"position":"before"                        
				},
				{
					"iconContent":"e625",
					"label":"icon_floppy_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e626",
					"label":"icon_flowchart_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e627",
					"label":"icon_folder_download",  
					"position":"before"                        
				},
				{
					"iconContent":"e628",
					"label":"icon_folder_upload", 
					"position":"before"                      
				},
				{
					"iconContent":"e629",
					"label":"icon_folder-add",  
					"position":"before"                     
				},
				{
					"iconContent":"e62a",
					"label":"icon_folder-open",  
					"position":"before"                        
				},
				{
					"iconContent":"e62b",
					"label":"icon_gift",  
					"position":"before"                        
				},
				{
					"iconContent":"e62d",
					"label":"icon_globe_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e62e",
					"label":"icon_grid-2x2",  
					"position":"before"                        
				},
				{
					"iconContent":"e62f",
					"label":"icon_grid-3x3",  
					"position":"before"                        
				},
				{
					"iconContent":"e630",
					"label":"icon_group",  
					"position":"before"                        
				},
				{
					"iconContent":"e631",
					"label":"icon_heart",  
					"position":"before"                        
				},
				{
					"iconContent":"e637",
					"label":"icon_hourglass",  
					"position":"before"                        
				},
				{
					"iconContent":"e632",
					"label":"icon_house", 
					"position":"before"                      
				},
				{
					"iconContent":"e633",
					"label":"icon_id_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e63a",
					"label":"icon_image",  
					"position":"before"                        
				},
				{
					"iconContent":"e634",
					"label":"icon_info",  
					"position":"before"                        
				},
				{
					"iconContent":"e635",
					"label":"icon_key",  
					"position":"before"                        
				},
				{
					"iconContent":"e636",
					"label":"icon_lifesaver",  
					"position":"before"                        
				},
				{
					"iconContent":"e638",
					"label":"icon_lightbulb",  
					"position":"before"                        
				},
				{
					"iconContent":"e639",
					"label":"icon_like_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e63b",
					"label":"icon_lock-open",  
					"position":"before"                        
				},
				{
					"iconContent":"e63c",
					"label":"icon_lock",  
					"position":"before"                        
				},
				{
					"iconContent":"e63d",
					"label":"icon_mail", 
					"position":"before"                      
				},
				{
					"iconContent":"e63e",
					"label":"icon_map",  
					"position":"before"                     
				},
				{
					"iconContent":"e63f",
					"label":"icon_mic",  
					"position":"before"                        
				},
				{
					"iconContent":"e640",
					"label":"icon_minus_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e641",
					"label":"icon_mobile",  
					"position":"before"                        
				},
				{
					"iconContent":"e642",
					"label":"icon_mug_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e643",
					"label":"icon_music",  
					"position":"before"                        
				},
				{
					"iconContent":"e644",
					"label":"icon_pause_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e645",
					"label":"icon_pencil_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e646",
					"label":"icon_pens_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e647",
					"label":"icon_percent_alt", 
					"position":"before"                      
				},
				{
					"iconContent":"e648",
					"label":"icon_phone",  
					"position":"before"                     
				},
				{
					"iconContent":"e649",
					"label":"icon_pin",  
					"position":"before"                        
				},
				{
					"iconContent":"e64a",
					"label":"icon_plus_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e64b",
					"label":"icon_printer-alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e64c",
					"label":"icon_profile",  
					"position":"before"                        
				},
				{
					"iconContent":"e64d",
					"label":"icon_pushpin",  
					"position":"before"                        
				},
				{
					"iconContent":"e64e",
					"label":"icon_puzzle_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e64f",
					"label":"icon_question_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e650",
					"label":"icon_ribbon",  
					"position":"before"                        
				},
				{
					"iconContent":"e651",
					"label":"icon_rook", 
					"position":"before"                      
				},
				{
					"iconContent":"e652",
					"label":"icon_search_alt",  
					"position":"before"                     
				},
				{
					"iconContent":"e653",
					"label":"icon_shield_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e654",
					"label":"icon_star",  
					"position":"before"                        
				},
				{
					"iconContent":"e655",
					"label":"icon_stop_alt",  
					"position":"before"                        
				},
				{
					"iconContent":"e656",
					"label":"icon_tablet",  
					"position":"before"                        
				},
				{
					"iconContent":"e657",
					"label":"icon_tag",  
					"position":"before"                        
				},
				{
					"iconContent":"e658",
					"label":"icon_tags",  
					"position":"before"                        
				},
				{
					"iconContent":"e659",
					"label":"icon_tool",  
					"position":"before"                        
				},
				{
					"iconContent":"e65a",
					"label":"icon_toolbox",  
					"position":"before"                        
				},
				{
					"iconContent":"e65b",
					"label":"icon_tools", 
					"position":"before"                      
				},
				{
					"iconContent":"e65c",
					"label":"icon_trash",  
					"position":"before"                     
				},
				{
					"iconContent":"e65d",
					"label":"icon_upload",  
					"position":"before"                        
				},
				{
					"iconContent":"e65e",
					"label":"icon_vol-mute",  
					"position":"before"                        
				},
				{
					"iconContent":"e65f",
					"label":"icon_volume-high",  
					"position":"before"                        
				},
				{
					"iconContent":"e660",
					"label":"icon_volume-low",  
					"position":"before"                        
				},
				{
					"iconContent":"e661",
					"label":"icon_wallet_alt",  
					"position":"before"                        
				},
				{


					"iconContent":"e662",
					"label":"icon_zoom",  
					"position":"before"                        
				},
				{
					"iconContent":"e663",
					"label":"icon_zoom-out",  
					"position":"before"                        
				}
			]
		}  
	]    
}